Don't try to remove residue if not present
See the following error. From examining the PDB, which is pdb 7p4b, the error appears to come from having a PDB with multiple chains. Specifically, there is a warning generated from the TER line for 277. The specific error appears to be because mutatex is trying to remove PA277_PC277_PG277 from the list of unique residues, I haven't deeply investigated, my guess is that PA277, PC277, and PG277 are each stored in unique_residues separately.


INFO:root:run PA277_PC277_PG277 was terminated before completing
WARNING:root:The following mutation runs failed to complete. The corresponding positions in sequence will be skipped.
WARNING:root:   PA277_PC277_PG277
Traceback (most recent call last):
  File "/home/jsafer/mutatex_env/bin/mutatex", line 4, in <module>
    __import__('pkg_resources').run_script('MutateX==0.8', 'mutatex')
  File "/home/jsafer/mutatex_env/lib/python3.9/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/jsafer/mutatex_env/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/home/jsafer/mutatex_env/lib/python3.9/site-packages/MutateX-0.8-py3.9.egg/EGG-INFO/scripts/mutatex", line 384, in <module>
ValueError: list.remove(x): x not in list